apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: regular-encourager
  name: regular-encourager
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: regular-encourager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: regular-encourager
    spec:
      containers:
      - env:
        - name: GREETING_FROM_ENVIRONMENT_VARIABLE
          value: HOLA!
        - name: FAREWELL_FROM_ENVIRONMENT_VARIABLE
          valueFrom:
            configMapKeyRef:
              key: FAREWELL_FROM_ENVIRONMENT_VARIABLE
              name: re-config
        - name: ENCOURAGE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: regenc-secret
        image: 1dropaflame/encourage:1.0.9
        imagePullPolicy: IfNotPresent
        name: encourage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/c/Users/Anil/Documents/Projects/regular-encourager
          name: config-volume
        - mountPath: /app/logs
          name: shared-data
      - name: sidecar
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /pod-data/logging_date.txt; sleep 10;done"]
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data          
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: myindex
        name: config-volume
      - name: shared-data
        emptyDir: {}  

