apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-03-17T02:46:40Z"
  generateName: regular-encourager-76c8f4655c-
  labels:
    app: regular-encourager
    pod-template-hash: 76c8f4655c
  name: regular-encourager-76c8f4655c-mjtx7
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: regular-encourager-76c8f4655c
    uid: e89c6af9-8bf1-456e-b509-a83bf1f87a71
  resourceVersion: "165705"
  uid: e1f84b2f-75ba-4ff5-857f-f46f53094021
spec:
  containers:
  - image: 1dropaflame/encourage:1.0.4
    imagePullPolicy: IfNotPresent
    name: encourage
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gxs89
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-gxs89
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-17T02:46:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-17T02:46:41Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-17T02:46:41Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-17T02:46:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://13b4838f10c379b1bda05b4ec8d23a3f1430fb32a5940f1e80f4c1a3adc5ca6e
    image: 1dropaflame/encourage:1.0.4
    imageID: docker-pullable://1dropaflame/encourage@sha256:88d97c7858112c491cb2f6bde730db8acc5d24e11c18dad23e88553daf7b4a1e
    lastState: {}
    name: encourage
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-17T02:46:41Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.48
  podIPs:
  - ip: 10.244.0.48
  qosClass: BestEffort
  startTime: "2023-03-17T02:46:40Z"
