apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: regular-encourager
  name: regular-encourager
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: regular-encourager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: regular-encourager
    spec:
      containers:
      - env:
        - name: GREETING_FROM_ENVIRONMENT_VARIABLE
          value: HOLA!
        image: 1dropaflame/encourage:1.0.4
        imagePullPolicy: IfNotPresent
        name: encourage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
