drop table ENCOURAGEMENT if exists;
drop TYPE Category if exists;
drop TYPE Tone if exists;
drop TYPE Topic if exists;
CREATE TYPE Category AS ENUM('WhoIAmInChrist','Default');
CREATE TYPE Tone AS ENUM('Default', 'Uplifting', 'Urging', 'Warning', 'Soothing', 'Comforting', 'Inspiring', 'Centering', 'Balanced');
CREATE TYPE Topic AS ENUM('Default', 'AcceptedInChrist', 'SignificantInChrist', 'SecureInChrist', 'NoAnxietyInChrist');
CREATE TABLE Encouragement(ID INT PRIMARY KEY, CATEGORY Category, TOPIC Topic, TONE Tone, MESSAGE VARCHAR(512));
INSERT INTO Encouragement VALUES(-1, 'Default', 'Default', 'Default', 'We walk by Faith, not by Sight');
INSERT INTO Encouragement VALUES(0,'WhoIAmInChrist','AcceptedInChrist','Uplifting','John 1:12 I am God''s child.');
INSERT INTO Encouragement VALUES(1,'WhoIAmInChrist','AcceptedInChrist','Uplifting','John 15:15 As a disciple, I am a friend of Jesus Christ.');
INSERT INTO Encouragement VALUES(2,'WhoIAmInChrist','AcceptedInChrist','Uplifting','Romans 5:1 I have been justified (declared righteous).');
INSERT INTO Encouragement VALUES(3,'WhoIAmInChrist','AcceptedInChrist','Uplifting','1 Corinthians 6:17 I am united with the Lord, and I am one with Him in spirit.');
INSERT INTO Encouragement VALUES(4,'WhoIAmInChrist','AcceptedInChrist','Uplifting','1 Corinthians 6:19-20 I have been bought with a price and I belong to God.');
INSERT INTO Encouragement VALUES(5,'WhoIAmInChrist','AcceptedInChrist','Uplifting','1 Corinthians 12:27 I am a member of Christ''s body.');
INSERT INTO Encouragement VALUES(6,'WhoIAmInChrist','AcceptedInChrist','Uplifting','Ephesians 1:3-8 I have been chosen by God and adopted as His child.');
INSERT INTO Encouragement VALUES(7,'WhoIAmInChrist','AcceptedInChrist','Uplifting','Colossians 1:13-14 I have been redeemed and forgiven of all my sins.');
INSERT INTO Encouragement VALUES(8,'WhoIAmInChrist','AcceptedInChrist','Uplifting','Colossians 2:9-10 I am complete in Christ.');
INSERT INTO Encouragement VALUES(9,'WhoIAmInChrist','AcceptedInChrist','Uplifting','Hebrews 4:14-16 I have direct access to the throne of grace through Jesus Christ.');
INSERT INTO Encouragement VALUES(10,'WhoIAmInChrist','SignificantInChrist','Uplifting','John 15:5 I am a branch of Jesus Christ, the true vine, and a channel of His life.');
INSERT INTO Encouragement VALUES(11,'WhoIAmInChrist','SignificantInChrist','Uplifting','John 15:16 I have been chosen and appointed to bear fruit.');
INSERT INTO Encouragement VALUES(12,'WhoIAmInChrist','SignificantInChrist','Uplifting','1 Corinthians 3:16 I am God''s temple.');
INSERT INTO Encouragement VALUES(13,'WhoIAmInChrist','SignificantInChrist','Uplifting','2 Corinthians 5:17-21 I am a minister of reconciliation for God.');
INSERT INTO Encouragement VALUES(14,'WhoIAmInChrist','SignificantInChrist','Uplifting','Ephesians 2:6 I am seated with Jesus Christ in the heavenly realm.');
INSERT INTO Encouragement VALUES(15,'WhoIAmInChrist','SignificantInChrist','Uplifting','Ephesians 2:10 I am God''s workmanship.');
INSERT INTO Encouragement VALUES(16,'WhoIAmInChrist','SignificantInChrist','Uplifting','Ephesians 3:12 I may approach God with freedom and confidence.');
INSERT INTO Encouragement VALUES(17,'WhoIAmInChrist','SignificantInChrist','Uplifting','Philippians 4:13 I can do all things through Christ, who strengthens me.');
INSERT INTO Encouragement VALUES(18,'WhoIAmInChrist','SecureInChrist','Uplifting','Romans 8:1-2 I am free from condemnation.');
INSERT INTO Encouragement VALUES(19,'WhoIAmInChrist','SecureInChrist','Uplifting','Romans 8:28 I am assured that God works for my good in all circumstances.');
INSERT INTO Encouragement VALUES(20,'WhoIAmInChrist','SecureInChrist','Uplifting','Romans 8:31-39 I am free from any condemnation brought against me and I cannot be separated from the love of God.');
INSERT INTO Encouragement VALUES(21,'WhoIAmInChrist','SecureInChrist','Uplifting','2 Corinthians 1:21-22 I have been established, anointed and sealed by God.');
INSERT INTO Encouragement VALUES(22,'WhoIAmInChrist','SecureInChrist','Uplifting','Colossians 3:1-4 I am hidden with Christ in God.');
INSERT INTO Encouragement VALUES(23,'WhoIAmInChrist','SecureInChrist','Uplifting','Philippians 1:6 I am confident that God will complete the good work He started in me.');
INSERT INTO Encouragement VALUES(24,'WhoIAmInChrist','SecureInChrist','Uplifting','Philippians 3:20 I am a citizen of heaven.');
INSERT INTO Encouragement VALUES(25,'WhoIAmInChrist','SecureInChrist','Uplifting','2 Timothy 1:7 I have not been given a spirit of fear but of power, love and a sound mind.');
INSERT INTO Encouragement VALUES(26,'WhoIAmInChrist','SecureInChrist','Uplifting','1 John 5:18 I am born of God and the evil one cannot touch me.');
INSERT INTO Encouragement VALUES(27,'WhoIAmInChrist','NoAnxietyInChrist','Uplifting','Don’t be anxious about anything: Philippians 4:6-7 "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus" (NIV).');
INSERT INTO Encouragement VALUES(28,'WhoIAmInChrist','NoAnxietyInChrist','Uplifting','Give God your worry: 1 Peter 5:6-7 " Humble yourselves, therefore, under God’s mighty hand, that he may lift you up in due time. Cast all your anxiety on him because he cares for you " (NIV).');
INSERT INTO Encouragement VALUES(29,'WhoIAmInChrist','NoAnxietyInChrist','Uplifting','He will sustain you in the storm: Psalm 55:22 " Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken" (NIV).');
INSERT INTO Encouragement VALUES(30,'WhoIAmInChrist','NoAnxietyInChrist','Uplifting','We can trust God completely: Proverbs 3:5-6"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight " (NIV).');
INSERT INTO Encouragement VALUES(31,'WhoIAmInChrist','NoAnxietyInChrist','Uplifting','God is bigger than our fearful hearts: Isaiah 35:4  "Say to those with fearful hearts, ''Be strong, do not fear; your God will come, he will come with vengeance; with divine retribution he will come to save you'' " (NIV).');
select * from ENCOURAGEMENT;